/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the service is up.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description Enabled providers with their circuit-breaker state, such as paused after a quota error.
         */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Scan
         * @description Upload a source file or a ``.zip`` and start scanning it.
         *
         *     Hosted models receive code only when ``allow_external`` is true.
         */
        post: operations["create_scan_api_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description A scan's status, with its counts, score and AI summary once finished.
         */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Scan
         * @description Stop the scan if it is running and delete the upload and everything derived from it.
         */
        delete: operations["delete_scan_api_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Events
         * @description The scan's events as server-sent events, replayed after ``Last-Event-ID``, then live.
         */
        get: operations["scan_events_api_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description The scan's files with reported finding counts, and the files that were skipped.
         */
        get: operations["list_files_api_scans__scan_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read File
         * @description The text of one of the scan's files, for the code viewer.
         */
        get: operations["read_file_api_scans__scan_id__files__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Every finding, including those dismissed, rejected or below the confidence threshold.
         */
        get: operations["list_findings_api_scans__scan_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Decide Finding
         * @description Accept, reject or restore a finding.
         */
        patch: operations["decide_finding_api_scans__scan_id__findings__finding_id__patch"];
        trace?: never;
    };
    "/api/scans/{scan_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Report
         * @description The report as a JSON, SARIF or HTML file download.
         */
        get: operations["download_report_api_scans__scan_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_scan_api_scans_post */
        Body_create_scan_api_scans_post: {
            /**
             * Allow External
             * @default false
             */
            allow_external: boolean;
            /** @default standard */
            depth: components["schemas"]["Depth"];
            /** File */
            file: string;
        };
        /**
         * BreakerState
         * @description Whether a provider receives traffic.
         * @enum {string}
         */
        BreakerState: "closed" | "open" | "half_open";
        /**
         * CallRecord
         * @description One attempt, for provenance in reports and the routing evaluation.
         *
         *     Records never contain prompts or responses, so they can be logged and stored.
         *
         *     Attributes:
         *         file_path: The file whose code the call was about, so reports can show which
         *             provider saw which file; ``None`` for calls about the whole project.
         */
        CallRecord: {
            /** Detail */
            detail: string | null;
            /** File Path */
            file_path: string | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Model */
            model: string;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /** Provider */
            provider: string;
            status: components["schemas"]["CallStatus"];
            task: components["schemas"]["Task"];
        };
        /**
         * CallStatus
         * @description Outcome of one attempt to use a provider.
         * @enum {string}
         */
        CallStatus: "ok" | "cached" | "rate_limited" | "quota_exhausted" | "auth_failed" | "misconfigured" | "unavailable" | "rejected" | "skipped";
        /**
         * Category
         * @description What kind of issue a finding describes.
         * @enum {string}
         */
        Category: "bug" | "security" | "style" | "performance" | "maintainability" | "typing";
        /**
         * Depth
         * @description How thoroughly models review a scan.
         * @enum {string}
         */
        Depth: "static" | "quick" | "standard" | "deep";
        /**
         * FileContent
         * @description The text of one extracted file.
         */
        FileContent: {
            /** Content */
            content: string;
            /** Language */
            language: string | null;
            /** Path */
            path: string;
        };
        /**
         * FileEntry
         * @description One extracted file, with how many reported findings it has.
         */
        FileEntry: {
            /** Findings */
            findings: number;
            highest_severity: components["schemas"]["Severity"] | null;
            /** Language */
            language: string | null;
            /** Lines */
            lines: number | null;
            /** Path */
            path: string;
        };
        /**
         * FileTree
         * @description The scan's files and the files left out of it.
         */
        FileTree: {
            /** Files */
            files: components["schemas"]["FileEntry"][];
            /** Skipped */
            skipped: components["schemas"]["SkippedFile"][];
        };
        /**
         * Finding
         * @description One issue at one location.
         *
         *     Attributes:
         *         id: Unique id.
         *         file_path: POSIX path relative to the upload root.
         *         start_line: First affected line, 1-based.
         *         end_line: Last affected line, inclusive.
         *         start_column: 1-based column where the issue starts, when the tool reports it.
         *         end_column: 1-based column where the issue ends, when the tool reports it.
         *         category: Kind of issue.
         *         severity: How urgent it is.
         *         title: One-line summary of at most 80 characters.
         *         message: What is wrong.
         *         rationale: Why it matters; filled in by LLM review.
         *         evidence: The offending code. Never contains a detected secret.
         *         rule_id: The producing tool's rule identifier, such as ``F401`` or ``B602``.
         *         sources: Tools or models that reported this issue.
         *         confidence: 0 to 1; deterministic rules report 1.0.
         *         status: Review state.
         *         cwe: CWE identifier such as ``CWE-78``, when known.
         *         suggestion: How to fix it, in a sentence; filled in by LLM review.
         *         verified_by: Models that independently confirmed an issue another model reported.
         *         ai_note: What AI review concluded when it questions the finding, such as why a
         *             model dismissed it or disagreed with it.
         */
        Finding: {
            /** Ai Note */
            ai_note: string | null;
            category: components["schemas"]["Category"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Cwe */
            cwe: string | null;
            /** End Column */
            end_column: number | null;
            /** End Line */
            end_line: number;
            /** Evidence */
            evidence: string | null;
            /** File Path */
            file_path: string;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Rationale */
            rationale: string | null;
            /** Rule Id */
            rule_id: string | null;
            severity: components["schemas"]["Severity"];
            /** Sources */
            sources: string[];
            /** Start Column */
            start_column: number | null;
            /** Start Line */
            start_line: number;
            /** @default open */
            status: components["schemas"]["FindingStatus"];
            /** Suggestion */
            suggestion: string | null;
            /** Title */
            title: string;
            /** Verified By */
            verified_by: string[];
        };
        /**
         * FindingDecision
         * @description A reviewer's decision on a finding. ``open`` restores a dismissed or rejected finding.
         */
        FindingDecision: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "accepted" | "rejected";
        };
        /**
         * FindingStatus
         * @description Where a finding stands in review.
         * @enum {string}
         */
        FindingStatus: "open" | "dismissed_by_ai" | "needs_review" | "accepted" | "rejected";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Service liveness and the running version.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * NotReported
         * @description Findings kept in the report but left out of its counts, by reason.
         */
        NotReported: {
            /**
             * Below Min Confidence
             * @default 0
             */
            below_min_confidence: number;
            /**
             * Dismissed By Ai
             * @default 0
             */
            dismissed_by_ai: number;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
        };
        /**
         * ProviderView
         * @description One enabled provider. ``external`` providers receive code only with consent.
         */
        ProviderView: {
            /** External */
            external: boolean;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Reason */
            reason: string | null;
            /** Reopens In Seconds */
            reopens_in_seconds: number;
            state: components["schemas"]["BreakerState"];
        };
        /**
         * ProvidersView
         * @description The enabled providers and whether models are real or mocked.
         */
        ProvidersView: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "mock";
            /** Providers */
            providers: components["schemas"]["ProviderView"][];
        };
        /**
         * QualityScore
         * @description The score, its grade and every input needed to recompute it.
         */
        QualityScore: {
            /** Complex Functions */
            complex_functions: number;
            /** Complexity Penalty */
            complexity_penalty: number;
            /** Finding Penalty */
            finding_penalty: number;
            /**
             * Formula
             * @default 100 - (25 x critical + 10 x high + 4 x medium + 1 x low) / max(1, KLOC) - 20 x share of functions with cyclomatic complexity >= 21
             */
            formula: string;
            /** Functions */
            functions: number;
            /**
             * Grade
             * @enum {string}
             */
            grade: "A" | "B" | "C" | "D" | "E";
            /** Kloc */
            kloc: number;
            /** Score */
            score: number;
        };
        /**
         * ReportCounts
         * @description Headline numbers. ``findings`` and the breakdowns count reported findings only.
         */
        ReportCounts: {
            /** By Category */
            by_category: {
                [key: string]: number;
            };
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /** Files Reviewed */
            files_reviewed: number;
            /** Files Scanned */
            files_scanned: number;
            /** Findings */
            findings: number;
            not_reported: components["schemas"]["NotReported"];
        };
        /**
         * ReportFormat
         * @description Download formats.
         * @enum {string}
         */
        ReportFormat: "json" | "sarif" | "html";
        /**
         * ReviewSummary
         * @description The executive summary of a review.
         */
        ReviewSummary: {
            /** Headline */
            headline: string;
            /**
             * Recommended Next Steps
             * @default []
             */
            recommended_next_steps: string[];
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Top Risks
             * @default []
             */
            top_risks: components["schemas"]["TopRisk"][];
        };
        /**
         * ScanDetail
         * @description A scan's status, and its headline results once it has finished.
         *
         *     ``calls`` lists every model call attempt, so clients can show which provider saw which file.
         */
        ScanDetail: {
            ai_summary: components["schemas"]["ReviewSummary"] | null;
            /**
             * Calls
             * @default []
             */
            calls: components["schemas"]["CallRecord"][];
            scan: components["schemas"]["ScanInfo"];
            score: components["schemas"]["QualityScore"] | null;
            summary: components["schemas"]["ReportCounts"] | null;
        };
        /**
         * ScanInfo
         * @description A scan's status and settings, as clients see them.
         */
        ScanInfo: {
            /** Allow External */
            allow_external: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            depth: components["schemas"]["Depth"];
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["ScanStatus"];
        };
        /**
         * ScanStatus
         * @description Where a scan is in its life.
         * @enum {string}
         */
        ScanStatus: "queued" | "running" | "done" | "failed";
        /**
         * Severity
         * @description How urgently an issue needs attention, most severe first.
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /**
         * SkipReason
         * @description Why a file was left out of the review. Skipping is not an error.
         * @enum {string}
         */
        SkipReason: "excluded_directory" | "lockfile" | "minified" | "too_large" | "binary" | "symlink" | "invalid_name" | "special_file" | "unreadable";
        /**
         * SkippedFile
         * @description A file that was present in the upload but not extracted.
         */
        SkippedFile: {
            /** Path */
            path: string;
            reason: components["schemas"]["SkipReason"];
        };
        /**
         * Task
         * @description Kinds of LLM work, each routed to the providers best suited to it.
         * @enum {string}
         */
        Task: "review" | "style" | "verify" | "summarize";
        /**
         * TopRisk
         * @description One of the most important problems named in a summary.
         */
        TopRisk: {
            /**
             * Files
             * @default []
             */
            files: string[];
            /** Title */
            title: string;
            /**
             * Why
             * @default
             */
            why: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersView"];
                };
            };
        };
    };
    create_scan_api_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_scan_api_scans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: number | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_scans__scan_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_file_api_scans__scan_id__files__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_scans__scan_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_finding_api_scans__scan_id__findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_scans__scan_id__report_get: {
        parameters: {
            query?: {
                format?: components["schemas"]["ReportFormat"];
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
